propName = {'BackgroundColor', 'FontSize','HorizontalAlignment'};
propVal  = {       [.8 .8 .8],         11,              'right'};
boxVal   = {    [.95 .95 .95],         11,             'center'};
pnlpVal  = {       [.9 .9 .9],         11,              'right'};


prog      = 0;
natPic    = [];%imread('cover_nature.jpg');
firstCol  = 5;
txtWidth  = 100;
firstBox  = firstCol + txtWidth + 10;
boxWidth  = 120;
secondCol = firstCol + txtWidth  + boxWidth + 20;
secondBox = secondCol + txtWidth + 10;

% Generate Figure for run
    ft2dSet = figure('MenuBar', 'none', 'NumberTitle','off', ...
        'Name', 'Analysis of Shaper 2DIR Experiments','Position',[12 50 1000 600]);
    hd.param2Dbtn = uicontrol('Position',[40 550 50 30],'String','Main',...
        'Callback',@SwitchPanelsCB, 'TooltipString',...
        'Display Parameters for 2DIR Experiments');
    hd.paramTransbtn = uicontrol('Position',[100 550 90 30],'String','Transient',...
        'Callback',@SwitchPanelsCB, 'TooltipString',...
        'Display Parameters for Transient Experiments');    
    hd.paramPlotbtn = uicontrol('Position',[200 550 50 30],'String','Plots',...
        'Callback',@SwitchPanelsCB, 'TooltipString',...
        'Display Ploting parameters');
    hd.paramTweakbtn = uicontrol('Position',[260 550 90 30],'String','Tweaks',...
        'Callback',@SwitchPanelsCB, 'TooltipString',...
        'Display rarely changed parameters');
    
%%  Panels %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % 2d parametrs
    hd.Panel2D = uipanel('Parent',ft2dSet,'Units','points','FontSize',12,...
              'Position',[10 120 400 310], 'BorderType', 'beveledin');
    
    uicontrol('Parent',hd.Panel2D,'Style', 'text', 'Position',[firstCol 340 txtWidth 20],'String', ...
        'Starting t_1', propName,pnlpVal);
    hd.t1LowBox = uicontrol('Parent',hd.Panel2D,'Style', 'edit', 'Position',[firstBox 340 boxWidth 25],'String', ...
        '0 fs',propName,boxVal, 'TooltipString', 'Determines what the first t_1 time is. (fs)');
    uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[firstCol 310 txtWidth 20],'String', ...
        't_1 step', propName,pnlpVal, 'TooltipString', 'Sets the step for changing t_1 (fs)');
    hd.t1StepBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[firstBox 310 boxWidth 25],'String', ...
        '2 fs', propName,boxVal);
    uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[firstCol 280 txtWidth 20],'String', ...
        'Ending t_1', propName,pnlpVal);
    hd.t1HighBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[firstBox 280 boxWidth 25],'String', ...
        '400 fs', propName,boxVal,'TooltipString', 'Determines the last t_1 time (fs)');
    uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[firstCol 250 txtWidth 20],'String', ...
        'Rotating Frame', propName,pnlpVal);
    hd.rotFramBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[firstBox 250 boxWidth 25],'String', ...
        '0 cm^-1', propName,boxVal);
    uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[firstCol 220 txtWidth 20],'String', 'Molicule Prefix', ...
        propName,pnlpVal);
    hd.molPreBox = uicontrol('Parent',hd.Panel2D,'Style', 'edit', 'Position',[firstBox 220 boxWidth 25],'String', 'DMDC_',...
        propName,boxVal, 'TooltipString', 'Sets the Default root name for files (local only)'); 
    
    hd.expTypeBox = uicontrol('Parent',hd.Panel2D, 'Style', 'popupmenu', 'Position',[(secondCol+10) 340 (boxWidth+txtWidth) 25],'String', ...
        'Normal 2DIR|Trans. 2D|Pump-Probe|Chirp 2D|Rabi 2D|Other', 'Enable', 'on', 'UserData', 105, 'Value', 1, ...
        propName,boxVal, 'TooltipString', 'Sets the type of experiment', 'CallBack', @SetExpTypeCB);
    %uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[secondCol 310 txtWidth 20],'String', ...
    %    'Starting t_2', propName,pnlpVal, 'TooltipString', 'Sets the minimum t_2 time (ps)');
    %hd.t2LowBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[secondBox 310 boxWidth 25],'String', ...
    %    '0 ps',propName,boxVal, 'TooltipString', 'Sets the minimum t_2 time (ps)');
    %uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[secondCol 280 txtWidth 20],'String', ...
    %    't_2 Steps', propName,pnlpVal, 'TooltipString', 'Sets the number of t_2 steps');
    %hd.t2NumbBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[secondBox 280 boxWidth 25],'String', ...
    %    '1', propName,boxVal, 'TooltipString', 'Sets the number of t_2 steps');
    %uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[secondCol 250 txtWidth 20],'String', ...
    %    'Ending t_2', propName,pnlpVal, 'TooltipString', 'Sets the maximum t_2 time (ps)');
    %hd.t2HighBox = uicontrol('Parent',hd.Panel2D, 'Style', 'edit', 'Position',[secondBox 250 boxWidth 25],'String', ...
    %    '0 ps', propName,boxVal, 'TooltipString', 'Sets the maximum t_2 time (ps)');
    %uicontrol('Parent',hd.Panel2D, 'Style', 'text', 'Position',[secondCol 220 txtWidth 20],'String', ...
    
    
    hd.pcTAbtn = uicontrol('Parent',hd.Panel2D, 'Style', 'checkbox', 'Position',[20 180 (boxWidth+txtWidth) 20],'String', ...
        'Phase Cycle for Trans. Abs.','Value', 1,propName,pnlpVal,...
        'TooltipString', 'Sets the Shaper to Phase Cycle for Transient Absorbtion removal');
    hd.pcBGbtn = uicontrol('Parent',hd.Panel2D, 'Style', 'checkbox', 'Position',[20 150 (boxWidth+txtWidth) 20],'String', ...
        'Phase Cycle for background','Value', 1, propName,pnlpVal,...
        'TooltipString', 'Sets the Shaper to Phase Cycle for Background Probe Spectrum removal');
    hd.dfGeobtn = uicontrol('Parent',hd.Panel2D, 'Style', 'checkbox', 'Position',[20 120 (boxWidth+txtWidth) 20],'String', ...
        'Deflected Geometry', 'Value', 1, propName, pnlpVal, 'TooltipString', ... 
        'Tells the Shaper that we are using the Diflected Geometry for the Pump Pulse');

    
    %% Plots  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    hd.PanelPlot = uipanel('Parent',ft2dSet,'Units','points','FontSize',12,...
              'Position',[10 120 400 310], 'BorderType', 'beveledin', 'Visible', 'off');
    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[firstCol 340 txtWidth 20],'String', ...
        'Center Freq.', propName,pnlpVal);
    hd.wCenterBox = uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[firstBox 340 boxWidth+20 25],'String', ...
        '2000 cm^-1', 'Enable', 'off', ...
        propName,boxVal, 'TooltipString', 'Sets the center frequency of plots');
    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[firstCol 310 txtWidth 20],'String', ...
        'Freq. Width', propName,pnlpVal, 'TooltipString', 'Sets a frequency (cm^-1) spread of the plotted spectrum.');
    hd.wWidthBox = uicontrol('Parent',hd.PanelPlot, 'Style', 'edit', 'Position',[firstBox 310 boxWidth 25],'String', ...
        '50 cm^-1', propName,boxVal, 'TooltipString', 'Sets a frequency (cm^-1) width of plots.');

    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[firstCol 280 txtWidth 20],'String', ...
        'Ex. Shift', propName,pnlpVal, 'TooltipString', 'Add shift to the excitation frequency (cm^-1)');
    hd.weShiftCut = uicontrol('Parent',hd.PanelPlot, 'Style', 'edit', 'Position',[firstBox 280 boxWidth 25],'String', ...
        '10 cm^-1', propName,boxVal, 'TooltipString', 'Add a phase offest above this frequency (cm^-1)', 'Enable', 'on');
    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[secondCol 280 txtWidth 20],'String', ...
        'Det. Shift', propName,pnlpVal, 'TooltipString', 'Add this shift to detection fequencies');
    hd.wdShift = uicontrol('Parent',hd.PanelPlot, 'Style', 'edit', 'Position',[secondBox 280 boxWidth 25],'String', ...
        '-100 cm^-1', propName,boxVal, 'TooltipString', 'Add this shift to detection fequencies', 'Enable', 'on');
    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[firstCol 220 txtWidth 20],'String', ...
        'Phase Tweak', propName,pnlpVal, 'TooltipString', 'This is a complexx phase shift');
    hd.maskf0 = uicontrol('Parent',hd.PanelPlot, 'Style', 'edit', 'Position',[firstBox 220 boxWidth 25],'String', ...
        '-0.1', propName,boxVal, 'TooltipString', 'This is a complex phase shift', 'Enable', 'on');
    uicontrol('Parent',hd.PanelPlot, 'Style', 'text', 'Position',[secondCol 220 txtWidth 20],'String', ...
        'Gaus. Sigma', propName,pnlpVal, 'TooltipString', 'This is the frequency width for a Gaussian amplitude mask');
    hd.maskSig = uicontrol('Parent',hd.PanelPlot, 'Style', 'edit', 'Position',[secondBox 220 boxWidth 25],'String', ...
        '1.0e12 Hz', propName,boxVal, 'TooltipString', 'This is the frequency width for a Gaussian amplitude mask', 'Enable', 'on');
    
    % Time Evolution
     hd.PanelT2D = uipanel('Parent',ft2dSet,'Units','points','FontSize',12,...
               'Position',[10 120 400 310], 'BorderType', 'beveledin', 'Visible', 'off');
     uicontrol('Parent',hd.PanelT2D,'Style', 'text', 'Position',[firstCol 340 txtWidth 20],'String', ...
         'Preview Spec', propName,pnlpVal);
     hd.runPlotBox = uicontrol('Parent',hd.PanelT2D,'Style', 'edit', 'Position',[firstBox 340 boxWidth 25],'String', ...
         '1',propName,boxVal, 'TooltipString',...
         'Determines which spectra is used for previews');
     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 220 txtWidth 20],'String', ...
         'Population E', propName,pnlpVal, 'TooltipString', 'Set the time spacing (fs) for a extra pulse experiments.');
     hd.popExcite =uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 220 boxWidth 25],'String', ...
         '2000 cm^-1', propName,boxVal, 'TooltipString', 'Set the center excitation wavelength for a population');
     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 190 txtWidth 20],'String', ...
         'Population W', propName,pnlpVal, 'TooltipString', 'Set the phase for a Rabi Pre Pulse experiment.');
     hd.popDetect  = uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 190 boxWidth 25],'String', ...
         '2000 cm^-1', propName,boxVal, 'TooltipString', 'Set the center detection wavelength for a population.');
     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 160 txtWidth 20],'String', ...
         'Pop. Width', propName,pnlpVal, 'TooltipString', 'Set the number of pulses for a Rabi Pre Pulse experiment.');
     hd.popWide  = uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 160 boxWidth 25],'String', ...
         '4 cm^-1', propName,boxVal, 'TooltipString', 'Set the width of the population square');
%     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 130 txtWidth 20],'String', ...
%         'Stuff', propName,pnlpVal, 'TooltipString', 'Set the chirp (fs^2) for a chirp + 2DIR experiment & pump probe.');
%     hd.chirpPP =uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 130 boxWidth 25],'String', ...
%         '0 fs^2', propName,boxVal, 'TooltipString', 'Set the chirp (fs^2) for a chirp + 2DIR experiment & pump probe.');
%     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 100 txtWidth 20],'String', ...
%         'Chirp Step', propName,pnlpVal, 'TooltipString', 'Set the step size for a chirp + 2DIR experiment.');
%     hd.chirpNum  = uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 100 boxWidth 25],'String', ...
%         '20', propName,boxVal, 'TooltipString', 'Set the step size for a chirp + 2DIR experiment.');
%     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[firstCol 70 txtWidth 20],'String', ...
%         'Chirp High', propName,pnlpVal, 'TooltipString', 'Set the maximum chirp (fs^2) for a chirp + 2DIR experiment.');
%     hd.chirpHigh  = uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[firstBox 70 boxWidth 25],'String', ...
%         '50000 fs^2', propName,boxVal, 'TooltipString', 'Set the maximum chirp (fs^2) for a chirp + 2DIR experiment.'); 
%     uicontrol('Parent',hd.PanelT2D, 'Style', 'text', 'Position',[secondCol 220 txtWidth 20],'String', ...
%         'PrePulse Ratio', propName,pnlpVal, 'TooltipString', 'Set the e-firld ratio to go to pre-2D pulses');
%     hd.prePulseRatio =uicontrol('Parent',hd.PanelT2D, 'Style', 'edit', 'Position',[secondBox 220 boxWidth 25],'String', ...
%         '0.5', propName,boxVal, 'TooltipString', 'Set the e-firld ratio to go to pre-2D pulses', 'Enable', 'on');
%     
%     % Tweaks
%     hd.PanelTw = uipanel('Parent',ft2dSet,'Units','points','FontSize',12,...
%               'Position',[10 120 400 310], 'BorderType', 'beveledin', 'Visible', 'off');
%     uicontrol('Parent',hd.PanelTw, 'Style', 'text', 'Position',[firstCol 340 txtWidth 20],'String', ...
%         'RF Frequency', propName,pnlpVal, 'TooltipString', 'Sets the carrier RF Frequency');
%     hd.rfFreqpBox = uicontrol('Parent',hd.PanelTw, 'Style', 'edit', 'Position',[firstBox 340 boxWidth 25],'String', ...
%         '90.5e9 Hz ', propName,boxVal, 'TooltipString', 'Sets the carrier RF Frequency (Hz)');
%     uicontrol('Parent',hd.PanelTw, 'Style', 'text', 'Position',[firstCol 310 txtWidth 20],'String','RF Max. Amp.',...
%         propName,pnlpVal, 'TooltipString', 'Sets the carrier RF Maximum Amplitude (arb)');
%     hd.maxAmpBox = uicontrol('Parent',hd.PanelTw, 'Style', 'edit', 'Position',[firstBox 310 boxWidth 25],'String', ...
%         '1250', propName,boxVal, 'TooltipString', 'Sets the carrier RF Maximum Amplitude (arb)');  
%     uicontrol('Parent',hd.PanelTw,'Style', 'text', 'Position',[firstCol 280 txtWidth 20],'String', ...
%         'RF Lin. Shift', propName,pnlpVal, 'TooltipString', 'Sets the carrier RF Shift (Hz)');
%     hd.linShftBox = uicontrol('Parent',hd.PanelTw,'Style', 'edit', 'Position',[firstBox 280 boxWidth 25],'String', ...
%         '0 Hz', propName,boxVal, 'TooltipString', 'Sets the carrier RF Shift');
%     uicontrol('Parent',hd.PanelTw,'Style', 'text', 'Position',[firstCol 250 txtWidth 20],'String', ...
%         'Lin Chirp Cor.', propName,pnlpVal, 'TooltipString', 'Corrects for linear chirp (fs^2)');
%     hd.linChrpBox = uicontrol('Parent',hd.PanelTw,'Style', 'edit', 'Position',[firstBox 250 boxWidth 25],'String', ...
%         '98000 fs^2', propName,boxVal, 'TooltipString', 'Corrects for linear chirp (fs^2)');
%     uicontrol('Parent',hd.PanelTw,'Style', 'text', 'Position',[firstCol 220 txtWidth 20],'String', ...
%         'Quad Chirp Cor', propName,pnlpVal, 'TooltipString', 'Corrects for linear chirp (fs^2)');
%     hd.qudChrpBox = uicontrol('Parent',hd.PanelTw,'Style', 'edit', 'Position',[firstBox 220 boxWidth 25],'String', ...
%         '0 fs^3', propName,boxVal, 'TooltipString', 'Corrects for quadratic chirp (fs^3)');
%     uicontrol('Parent',hd.PanelTw,'Style', 'text', 'Position',[firstCol 190 txtWidth 20],'String', ...
%         'Spec Cleans', propName,pnlpVal, 'TooltipString', 'Number of blank pulses to output to clean the spectrometer');
%     hd.SpecClnBox = uicontrol('Parent',hd.PanelTw,'Style', 'edit', 'Position',[firstBox 190 boxWidth 25],'String', ...
%         '20', propName,boxVal, 'TooltipString', 'Number of blank pulses to output to clean the spectrometer');
%     uicontrol('Parent',hd.PanelTw, 'Style', 'text', 'Position',[firstCol 160 txtWidth 20],'String', ...
%         '2D pulse Ratio', propName,pnlpVal, 'TooltipString', 'first 2D pulse is x*total efield, second is (1-x) ');
%     hd.ratio2D = uicontrol('Parent',hd.PanelTw, 'Style', 'edit', 'Position',[firstBox 160 boxWidth 25],'String', ...
%         '0.50', propName,boxVal, 'TooltipString', 'first 2D pulse is x*total efield, second is (1-x) ', 'Enable', 'off');
%     hd.saveWaves = uicontrol('Parent',hd.PanelTw, 'Style', 'checkbox', 'Position',[(firstCol+35) 130 (boxWidth+txtWidth) 20],'String', ...
%         'Save CompuGen OBJ','Value', 1,propName,pnlpVal,...
%         'TooltipString', 'If true, the program will save a local copy of the compugen Object for analysis');
%     uicontrol('Parent',hd.PanelTw, 'Style', 'text', 'Position',[firstCol 100 txtWidth 20],'String', ...
%         'Save file', propName,pnlpVal, 'TooltipString', 'Local Files saved under this name in cd');
%     hd.locSave = uicontrol('Parent',hd.PanelTw, 'Style', 'edit', 'Position',[firstBox 100 boxWidth 25],'String', ...
%         'SpecInf_1', propName,boxVal, 'TooltipString', 'Local Files saved under this name in cd', 'Enable', 'on');
%     uicontrol('Parent',hd.PanelTw, 'Style', 'text', 'Position',[secondCol 340 txtWidth 20],'String', ...
%         'Crystal Length', propName,pnlpVal, 'TooltipString', 'Crystal Length in shaper pixels');
%     hd.crystalLen = uicontrol('Parent',hd.PanelTw, 'Style', 'edit', 'Position',[secondBox 340 boxWidth 25],'String', ...
%         '800', propName,boxVal, 'TooltipString', 'Crystal length in shaper pixels', 'Enable', 'on');
%     hd.exClock = uicontrol('Parent',hd.PanelTw, 'Style', 'checkbox', 'Position',[(secondCol+35) 310 (boxWidth+txtWidth) 20],'String', ...
%         'Use External Clock','Value', 1,propName,pnlpVal,...
%         'TooltipString', 'If true, the Compugen Board will require an external clock source');

     
    %%  Set 3 within the Setup Dialog box.  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    hd.Loadbtn = uicontrol('Position',[800 565 150 30],'String','Load Exp',...
        'Callback',@LoadExpScript, 'TooltipString',...
        'Load parameters from an Experiment file');
    hd.Processbtn = uicontrol('Position',[800 530 150 30],'String','Pulse Pair',...
        'Callback',@ProcessScript, 'TooltipString',...
        'Process loaded Data');
     hd.Plotbtn = uicontrol('Position',[800 530 150 30],'String','Pulse Pair',...
        'Callback',@PlotScript, 'TooltipString',...
        ' Plot Processed Data');   
    
    
    % expType higher up?
    
  %% bottom stuff  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    hd.canc = uicontrol('Position',[(firstCol+100) 20 200 40],'String','CANCEL',...
        'ForegroundColor', 'r','Callback',@SetScanCanceled, 'TooltipString','Click to Quit');
    hd.cont = uicontrol('Position',[(firstCol+200+100+40) 20 200 40],'String','Start',...
        'Callback',@ContinueCB,'TooltipString','Click to Start Data run');
    
   %% Stuff to display while running   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%    hd.expProg = uicontrol('Style', 'pushbutton', 'Position',[40 80 600 40],...
%        'Enable','inactive','CData',prog, propName,boxVal,...
%        'TooltipString', 'Shows progress throughout the data output session.');
    hd.expTxt = uicontrol('Style', 'text', 'Position',[40 120 600 20], 'String', 'Setup Analysis Parametrs',...
        'HorizontalAlignment', 'left','BackgroundColor',[.8 .8 .8], 'FontWeight', 'bold');
    %% Ending stuff  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%    hd.sendNature = uicontrol('Position',[770 20 200 250],'String','Submit Data',...
%        'Enable',dispNature, 'Visible', dispNature, 'CData', natPic, 'FontSize', 20, 'FontWeight', 'bold',...
%        'ForegroundColor', [.1 .1 .1],...
%        'TooltipString', 'Quit.  It is left as an exercise to the reasearcher to submit data to journals.');

guidata(ft2dSet, hd)


settingList = [ hd.cont hd.t1LowBox hd.t1StepBox hd.t1HighBox hd.rotFramBox...
    hd.pcTAbtn hd.pcBGbtn hd.dfGeobtn hd.molPreBox];